name: Update App Icon and Build APK

on:
  push:
    branches:
      - main 

jobs:
  update-icon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'

    - name: Fetch App Icon
      run: |
        curl -o assets/app_icon.png https://www.designer-daily.com/wp-content/uploads/2013/07/20-app.jpg
      
    - name: Set up flutter_launcher_icons
      run: flutter pub get

    - name: Generate Launcher Icon
      run: flutter pub run flutter_launcher_icons:main

    - name: Build APK
      run: flutter build apk --release

    - name: List build directory 
      run: |
        ls -l build/app/outputs/flutter-apk
